export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_FIRST = 'FETCH_TASK_FIRST';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';